# Use trusty (for recent pandoc)
#   https://docs.travis-ci.com/user/trusty-ci-environment/
dist: trusty
#
# Use full virtualisation
sudo: true
## Use docker image for speed
## When pandoc whitelisted:
##  https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-trusty
## Issue here:
##  https://github.com/travis-ci/apt-package-whitelist/issues/3762
#sudo: false
#group: beta
#
# C includes autotools and make by default
language: ruby
rvm:
  - 2.2
#
# Extra packages
addons:
  apt:
    packages:
    - pandoc
#
# Setup environment
before_install:
 # Decrypt our private files for CI use only
 - openssl aes-256-cbc -K $encrypted_ff0fa8642958_key -iv $encrypted_ff0fa8642958_iv -in .travis/travis_rsa.enc -out .travis/travis_rsa -d
 - eval "$(ssh-agent -s)"        # start the ssh agent
 - chmod 600 .travis/travis_rsa  # add our key
 - ssh-add .travis/travis_rsa    # add our key
 - rm -f .travis/travis_rsa      # remove to prevent leaks
 # WARNING: Any changes to the above 5 lines should be monitored closely
 - ssh-keyscan -H firehol.org >> ~/.ssh/known_hosts
 #
 # Install nanoc and other dependencies
 - gem install nanoc --version 3.8.0
 - gem install pandoc-ruby nokogiri
 # These have special meaning on the server, so disallow branches so named
 - test "$TRAVIS_BRANCH" != "www"
 - test "$TRAVIS_BRANCH" != "download"
 - test "$TRAVIS_BRANCH" != "static"
 - test "$TRAVIS_BRANCH" != "ssl"
 - test "$TRAVIS_BRANCH" != "webalizer"
 - test "$TRAVIS_BRANCH" != "tmp"
#
# Run
script:
 - make
#
# Copy to firehol.org for deployment
after_success:
 - mv output "$TRAVIS_BRANCH"
 - sed -e "s/NAME/$TRAVIS_BRANCH/" nginx.conf > "$TRAVIS_BRANCH".conf
 - "if [ $TRAVIS_PULL_REQUEST = false -a \"$TRAVIS_BRANCH\" != \"\" ]; then ssh travis@firehol.org mkdir -p website/$TRAVIS_BRANCH/ && rsync -a $TRAVIS_BRANCH $TRAVIS_BRANCH.conf travis@firehol.org:website/$TRAVIS_BRANCH/ && ssh travis@firehol.org touch website/$TRAVIS_BRANCH/complete.txt; fi;"
